---
- name: Configure tutorial.md file paths
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    HOME_DIR: "{{ '~' | expanduser }}"
    WORK_DIR: "{{ playbook_dir | dirname }}"

  tasks:
  - name: Update template paths
    template:
      src: "{{ playbook_dir }}/tutorial.md.j2"
      dest: "{{ WORK_DIR }}/tutorial.md"
